### PR TITLE
Speed up initialization of workflow analyses and speed up unit tests

### PR DESCRIPTION
**Pull request by koenderks**

### CODE REVIEW

**Comment by koenderks** [comment]
Currently with the anchors removed, the alignment is off in some cases . For example: 
image

**Review by JorisGoosen — APPROVED** [review]

**Comment by JorisGoosen** [comment]
This all looks good but it would be nice if the unittests confirmed this.
I just fixed up jaspResults for that so when @TimKDJ is back in action tomorrow he might be able to get those running again.

@koenderks if you've run the tests locally and they work then I am OK with this being squash+merged otherwise we wait for the fix to jaspTools

**Comment by koenderks** [comment]
The unit tests pass locally but I'll wait until I can install the developer module again to see the centering of the radio buttons first

**Comment by koenderks** [comment]
I was able to load the developer module and the centering of the radio buttons is fine.

**Pull request merged**
