### PR TITLE
Add github token as PAT in workflow

### PR DESCRIPTION
**Pull request by koenderks**

### CODE REVIEW

**Comment by AlexanderLyNL** [comment]
Is there a specific reason why a github token needs adding?

**Comment by koenderks** [comment]
> Is there a specific reason why a github token needs adding?

Yes, see the unit test failures in https://github.com/jasp-stats/jaspAudit/runs/3263108141, https://github.com/jasp-stats/jaspAudit/runs/3263108187, and https://github.com/jasp-stats/jaspAudit/runs/3263108232. 

I came across this in my own repositories as well, so maybe this is required for all submodules.

**Comment by AlexanderLyNL** [comment]
Perhaps Don or Joris can help you with this.

**Comment by koenderks** [comment]
Well I think this applies to all submodules, see now also the failing test for bain: https://github.com/jasp-stats/jaspBain/runs/3268755256

**Comment by AlexanderLyNL** [comment]
If it applies to all submodules then it might be good for Don or Joris to fix this globally. It's the weekend and you can/should take some time off.

**Comment by vandenman** [comment]
> If it applies to all submodules then it might be good for Don or Joris to fix this globally. 

I'm not sure if we can set one globally. And even if we'd set one global GITHUB_PAT then sooner or later we'll get rate-limited. The fix Koen used is the same as I'm using in https://github.com/jasp-stats/jaspAnova/pull/64. I think this is actually a good (albeit laborious) solution because the `GITHUB_PAT` is specific to each repository so getting rate-limited is very unlikely. Maybe we could extract the `GITHUB_PAT` in the jasp-action, I'll take a look at that.

**Comment by koenderks** [comment]
@vandenman Do you have any idea why this has changed all the sudden? Something must have changes in GitHub actions I presume?

**Review by vandenman — APPROVED** [review]

**Pull request merged**
