### PR TITLE
Put back scrolling in audit workflow data viewer

### PR DESCRIPTION
**Pull request by koenderks**
Closes https://github.com/jasp-stats/INTERNAL-jasp/issues/2517

### CODE REVIEW

**Comment by JorisGoosen** [comment]
Ok, so the scrolling thing works, but then I get this error:
Screenshot 2024-05-01 at 10 42 09

**Comment by JorisGoosen** [comment]
But that error is independent of this change so ill merge this

**Review by JorisGoosen — APPROVED** [review]

**Comment by koenderks** [comment]
> Ok, so the scrolling thing works, but then I get this error: Screenshot 2024-05-01 at 10 42 09
> 
> [kaputAudit.jasp.zip](https://github.com/jasp-stats/jaspAudit/files/15175395/kaputAudit.jasp.zip)

That happend when you click through the workflow too fast, apparently the R code has not finished running yet. I encountered it before, refreshing the workflow solves this problem.

**Comment by JorisGoosen** [comment]
Ah, so, I then reloaded the file and refreshed with the pre-height version and got the same error?
But anyway, if you're familiar with it then its fine.

**Pull request merged**
