### PR TITLE
Take more selection functionality from jfa package

### PR DESCRIPTION
**Pull request by koenderks**
- Adds a note when the sample export path is filled but the button is not checked
- Takes randomized functionality from the jfa package
- Disables randomize items option when rank variable is given

### CODE REVIEW

**Review by Kucharssim — APPROVED** [review]
Looks good to me!

**Comment by AlexanderLyNL** [comment]
This looks minor, but is it necessary for 0.16.1?

**Comment by koenderks** [comment]
Not required, but it would be nice to keep up to date with the jfa package.

**Comment by AlexanderLyNL** [comment]
I agree, but it's too late now. We'll move this PR forward to 0.16.1

**Pull request merged**
