### PR TITLE
Add error message for attribute sampling edge case

### PR DESCRIPTION
**Pull request by koenderks**
Add an error message for the case in https://github.com/jasp-stats/jasp-test-release/issues/2363

### CODE REVIEW

**Comment by RensDofferhoff** [comment]
The added error is not popping up for mw

**Comment by koenderks** [comment]
Hmm...weird...it should look like this:

image

**Comment by RensDofferhoff** [comment]
Ah my bad! its there. I just clicked through without seeing it.
We should perhaps disable the button that lets you continue.
But if you are happy with this its fine by me

**Comment by koenderks** [comment]
For now this is okay I think. We might consider changing the default materiality to 5 percent in the future or so if we have some more experience with how often this causes difficulties.

**Review by RensDofferhoff — APPROVED** [review]

**Pull request merged**
