### PR TITLE
Change the default variable type to binary and remove the sample when evaluating with summary statistics or binary outcomes

### PR DESCRIPTION
**Pull request by koenderks**

### CODE REVIEW

**Comment by TimKDJ** [comment]
`some latest changes` is a bit of a vague commit message...
Can you try to make this a little more specific (future us will appreciate it greatly)?

**Comment by koenderks** [comment]
Like this? :p

**Comment by TimKDJ** [comment]
Beautiful!

**Comment by TimKDJ** [comment]
Oh wait I meant the commit issue, not the pull request title. Oh well, it's merged now

**Comment by koenderks** [comment]
Whoops

**Pull request merged**
