### PR TITLE
Add DOI for paper

### PR DESCRIPTION
**Pull request by koenderks**
Some edits to the README

### CODE REVIEW

**Comment by AlexanderLyNL** [comment]
For some reason the unit test failed on Ubuntu, which it shouldn't of course. It looks like a configuration error. I'm justs going to rerun the unit tests again. If the error occurs again, I'll ask help from a higher power, i.e., Don. 

Error: Error in loadNamespace(x) : there is no package called ‘remotes’

**Comment by koenderks** [comment]
Yes, its all over github. I'm getting the same errors with the packages.

**Comment by koenderks** [comment]
These things usually happen when a package just got updated on CRAN.
image

It will resolve itself.

**Comment by AlexanderLyNL** [comment]
@vandenman Did you change the configuration of Ubuntu on github? In this case it seems to fail on remotes, which I'd expect to be installed once devtools is installed. Do you know what's happening here?

**Comment by vandenman** [comment]
The problem is that the website of Rstudio package manager (RSPM) is down (e.g., just try to go to https://packagemanager.rstudio.com/). That's where Linux retrieves its binaries from.

**Review by AlexanderLyNL — APPROVED** [review]

**Pull request merged**
